// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr8K6jB9SXk_LMY-5mCFTm20ScboBj_So',
    appId: '1:287050211855:web:e67b70d8153bcf2372397a',
    messagingSenderId: '287050211855',
    projectId: 'survey-118ab',
    authDomain: 'survey-118ab.firebaseapp.com',
    storageBucket: 'survey-118ab.appspot.com',
    measurementId: 'G-4BEXEL2QFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUnpWjHeN4g_5l4b80BQrVYRvvY9jBYZM',
    appId: '1:287050211855:android:1948e9530d0bffdb72397a',
    messagingSenderId: '287050211855',
    projectId: 'survey-118ab',
    storageBucket: 'survey-118ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYwHzhhVk_56YRPVLRMjO-zp4FFtE-J8',
    appId: '1:287050211855:ios:9f8f2b983310438a72397a',
    messagingSenderId: '287050211855',
    projectId: 'survey-118ab',
    storageBucket: 'survey-118ab.appspot.com',
    iosBundleId: 'com.example.portfolioWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeYwHzhhVk_56YRPVLRMjO-zp4FFtE-J8',
    appId: '1:287050211855:ios:1b554990ab1e964672397a',
    messagingSenderId: '287050211855',
    projectId: 'survey-118ab',
    storageBucket: 'survey-118ab.appspot.com',
    iosBundleId: 'com.example.portfolioWeb.RunnerTests',
  );
}
